name: CI/CD - Build -> Push to ECR -> Deploy ECS (CloudFormation)

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  CF_STACK_NAME: student-manager-stack-vpc
  CF_TEMPLATE_PATH: infrastructure/ecs-with-vpc.yaml

  # IMPORTANT: set this to your exact ECR repo name (you said it has namespace "travis")
  ECR_REPOSITORY: travis/student-manager

  CONTAINER_PORT: "3000"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (VocLabs)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "${ECR_REPOSITORY}" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "${ECR_REPOSITORY}" >/dev/null

      - name: Build and push image to ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

          echo "Building image: ${IMAGE_URI}"
          docker build -t "${IMAGE_URI}" .

          echo "Pushing image to ECR..."
          docker push "${IMAGE_URI}"

          echo "image_uri=${IMAGE_URI}" >> $GITHUB_OUTPUT

      - name: Deploy CloudFormation stack (ECS + ALB)
        run: |
          aws cloudformation deploy \
          --template-file "${CF_TEMPLATE_PATH}" \
          --stack-name "${CF_STACK_NAME}" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            ImageUri=${{ steps.build.outputs.image_uri }} \
            TaskExecutionRoleArn=${{ secrets.ECS_EXEC_ROLE_ARN }} \
            ContainerPort=3000 \
          --no-fail-on-empty-changeset

      - name: Dump CloudFormation events on failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name "${CF_STACK_NAME}" \
            --region "${{ secrets.AWS_REGION }}" \
            --query "StackEvents[0:25].[Timestamp,ResourceStatus,LogicalResourceId,ResourceStatusReason]" \
            --output table